bpatrik/pigallery2

frontend/translate/messages.ru.xlf

Please do not merge it right now, i wanna test it carefully

Russian translation

---

frontend/translate/messages.fr.xlf

New translation work after https://github.com/bpatrik/pigallery2/issues/85 addition.

Update related to #85

---

docker/alpine/Dockerfile

Build everything in the staged container and only copy the complete product to the final container.
Also reduced the size of the container threefold.
Created `data/{config,db,images,TEMP}` to make volumes possible for ease of use with docker and persistence of configurations.
`config.json` symlinks to `data/config/config.json` since I don'T know how to call for the config in different path
Example image can be found under `legsplits/pigallery2:latest`
If automated docker build is enabled, only needs pointing to the alpine Dockerfile.
Manual build `docker build -t pigallery2:latest -f- https://github.com/bpatrik/pigallery2.git < Dockerfile`
Compose
```
version: '2'
services:
pigalleryr:
container_name: pigalleryr
image: legsplits/pigallery2:latest
volumes:
- pig_conf:/app/data/config
- …
```

Alpine docker container

---

docker/alpine/Dockerfile

Since I don't know how to generate the config file without launching the server, this should do. Since it's only a build process, shouldn't matter too much.
Also, please add the alpine build to the docker hub autobuild process.

Update alpine dockerfile

---

.github/workflows/blank.yml

GHA allows 20 concurrent jobs. So make use of it.
https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#usage-limits

Speedup docker builds

---

angular.json

Issue #148: Enable cross origin requests for scripts

---

src/backend/routes/PublicRouter.ts
src/frontend/index.html

Will allow you to create better home screen and desktop shortcuts on desktop and mobile Chromium browsers.
See: https://web.dev/add-manifest/

Add web manifest

---

docker/docker-compose/with-mysql/docker-compose.yml

added missing space in docker-compose.yml

---

src/frontend/translate/messages.es.xlf

Add spanish translations to the frontend.

Add spanish translations

---

src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.css

I have a really hard time reading names of faces and captions.
Especially if the photo is bright and/or grayscale.
Here is a simple fix.

Add text shadow

---

src/frontend/translate/messages.sv.xlf

Updates and improvements to Swedish translation

Update swedish translation

---

src/frontend/app/ui/admin/admin.component.html

Add i18n to menu title string.

Enable tranlsation for settings sidebar menu title

---

src/frontend/translate/messages.it.xlf

I translated 60% of strings, I have no experience opening pull requests, I hope it's ok like this

Italian translation

---

src/frontend/app/ui/gallery/search/search-field/search-field.gallery.component.html

I hope it's ok to add this too. I think it's nice to also have search on click.

Search autocomplete suggestion on click

---

src/frontend/robots.txt
src/frontend/translate/messages.it.xlf

Hi, sorry for the late PR but suddenly I was buried in work.
Finished all the string translation to italian, then added another commit for the robots.txt that disallow indexing from search engines

Finalized italian translations + robots.txt

---

angular.json
src/frontend/translate/messages.pl.xlf

Please review & add to the project - provided Polish translation for pigallery2.

Polish translation added

---

package-lock.json
package.json
src/backend/middlewares/GalleryMWs.ts
src/backend/middlewares/RenderingMWs.ts
src/backend/routes/GalleryRouter.ts
src/common/config/public/ClientConfig.ts
src/frontend/app/ui/gallery/navigator/navigator.gallery.component.html
src/frontend/app/ui/gallery/navigator/navigator.gallery.component.ts
src/frontend/app/ui/settings/other/other.settings.component.html

- adds a config setting to Other/Misc for DownloadZip, defaults to False.
- when enabled, shows a download link on the navigation bar alongside the count of items
- download streams a zip of the current directory's media (photos and videos)
This resolves Issue #52

Download zip folder

---

package-lock.json
package.json
src/backend/model/database/sql/IndexingManager.ts
src/backend/model/database/sql/SearchManager.ts
src/backend/model/database/sql/enitites/FaceRegionEntry.ts

With this refactor running a search query should be 30-50% faster.

Improving search performance

---

docker/alpine/Dockerfile.build

As python in alpine 3.11 is version 2.x.x and python in alpine 3.13 have two versions ```python3``` and ```python2```.

Python version unavailable for alpine 3.13

---

README.md

Fixed an old URL in the README.md

update URL to the latest stable release

---

angular.json
src/frontend/translate/messages.cn.xlf

I've made a translation for Chinese.

add Chinese translation

---

src/frontend/index.html

Adding existing icon for Apple devices' homescreen as described in #351 .

apple-touch-icon

---

src/backend/model/database/sql/GalleryManager.ts
src/backend/model/threading/MetadataLoader.ts

see #409 for proposed solutions regarding "No negative EXIF ratings"

EXIF rating

---

angular.json
src/frontend/translate/messages.id.xlf

Add Indonesian translation, tell me if something i need to edit/add. 👍🏼

add id-translation

---

src/frontend/translate/messages.fr.xlf

translations: update french translation

---

src/frontend/app/ui/gallery/map/lightbox/lightbox.map.gallery.component.ts

This one is the good one :) Sorry for the confusion!

Gpx wpt mappoints with infinite loop fix

---

src/backend/middlewares/thumbnail/ThumbnailGeneratorMWs.ts
src/backend/model/database/sql/GalleryManager.ts
src/backend/model/database/sql/IndexingManager.ts
src/backend/model/database/sql/enitites/MediaEntity.ts
src/common/config/public/ClientConfig.ts
src/common/entities/MediaDTO.ts
src/common/entities/PersonDTO.ts
src/common/entities/PhotoDTO.ts
src/frontend/app/ui/gallery/Media.ts
src/frontend/app/ui/gallery/MediaIcon.ts
src/frontend/app/ui/gallery/cache.gallery.service.ts
src/frontend/app/ui/gallery/thumbnailManager.service.ts
test/backend/unit/model/sql/SearchManager.spec.ts
test/backend/unit/model/sql/TestHelper.ts

Expected to save 6% on the server result json size.
#437

Replace readyThumbnail filed with missingThumbnail bitmap.

---

src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.html
src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.ts

Use UTC for displaying image timestamps

---

package.json

Moving  xml2js from dev to runtime dependency

---

src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.css
src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.ts
src/frontend/app/ui/gallery/lightbox/lightbox.gallery.component.html
src/frontend/app/ui/gallery/lightbox/lightbox.gallery.component.ts
src/frontend/app/ui/gallery/lightbox/media/media.lightbox.gallery.component.html
src/frontend/app/ui/gallery/lightbox/media/media.lightbox.gallery.component.ts

#134
Also fixing play button animation.

Implementing next photo preloading

---

package.json

See https://github.com/joshwnj/ffprobe-static/pull/17

Upgrade ffprobe-static to support darwin arm64

---

src/frontend/app/ui/gallery/MediaIcon.ts

This PR tries to close issue #498 
I've tested the changes locally and they seem to work for question mark characters both in image and video files.
Feedback very welcome.

encoding of question mark character for media path - fixes issue #498

---

README.md

Hey, I have added a helpful reference link for installing node.js in the node.js section that I think will best add to your content and give your readers a more diverse understanding of the topic. I hope you will like this. Thank you.

Added one useful resource about installing node.js

---

src/backend/model/threading/MetadataLoader.ts
src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.ts

Fix problem with display of Exposure Value

---

README.md

Fixed link markdown

---

angular.json
docker/debian-buster/selfcontained/Dockerfile
src/frontend/translate/messages.nl.xlf

I also found a few fields that could not be translated ie. are not in the translation file, mainly stuff in the Search dialogue. I will open an issue for those.

Dutch translation

---

angular.json
src/frontend/translate/messages.ptbr.xlf

I've started the translation for a new language but didn't know if it was a problem using pt-br instead of ptbr. Since there's also pt-pt and had no other examples of dualities I went for ptbr without the -

A few brazilian portuguese translations - To Be Continued

---

src/frontend/app/ui/gallery/grid/photo/photo.grid.gallery.component.ts

 Add matchType to getPositionSearchQuery

---

src/backend/server.ts

Add SIGTERM handler

---

README.md

Source:
- https://github.com/bpatrik/pigallery2/issues/371#issuecomment-939366268

docs: add note about apache proxy and sub folders

---

src/backend/model/jobs/jobs/Job.ts
src/backend/model/jobs/jobs/TopPickSendJob.ts
src/backend/model/mediamessengers/EmailMediaMessenger.ts
src/common/BackendTexts.ts
src/common/config/private/MessagingConfig.ts
src/common/entities/job/JobDTO.ts
src/frontend/app/model/backendtext.service.ts
src/frontend/app/ui/settings/workflow/workflow.component.html
src/frontend/app/ui/settings/workflow/workflow.component.ts

It supports now multiple recipients and settings improved a bit.

Improving e-mail sending #683

---

demo/images/index.md
src/common/Utils.ts
src/frontend/app/app.module.ts
src/frontend/app/model/query.service.ts
src/frontend/app/ui/gallery/blog/blog.gallery.component.css
src/frontend/app/ui/gallery/blog/blog.gallery.component.html
src/frontend/app/ui/gallery/blog/blog.gallery.component.ts
src/frontend/app/ui/gallery/blog/blog.service.ts
src/frontend/app/ui/gallery/cache.gallery.service.ts
src/frontend/app/ui/gallery/content.service.ts
src/frontend/app/ui/gallery/contentLoader.service.ts
src/frontend/app/ui/gallery/filter/filter.service.ts
src/frontend/app/ui/gallery/gallery.component.css
src/frontend/app/ui/gallery/gallery.component.html
src/frontend/app/ui/gallery/gallery.component.ts
src/frontend/app/ui/gallery/grid/grid.gallery.component.html
src/frontend/app/ui/gallery/grid/grid.gallery.component.ts
src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.html
src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.ts
src/frontend/app/ui/gallery/navigator/navigator.gallery.component.html
src/frontend/app/ui/gallery/navigator/navigator.gallery.component.ts
src/frontend/app/ui/gallery/navigator/sorting.service.ts
src/frontend/app/ui/gallery/random-query-builder/random-query-builder.gallery.component.ts
src/frontend/app/ui/gallery/share/share.gallery.component.ts

You can tag section in the `*.md` files  with ``, like: `` to attach them to a date. 
Then, if you group by date, they will show up at the assigned day.
That part of the markdown will be removed from the main markdown at the top and shown only at that day.

Inline or groupped blog #711

---

docker/docker-compose/pigallery2-only/docker-compose.yml

Update docker-compose.yml to refer to version 3.9 rather than 3

---

docker/README.md

Fixes a typo in the docker README.
Thanks for the work on this! :)

Update README.md - Typo

---

src/frontend/app/model/backendtext.service.ts
src/frontend/app/ui/frame/frame.component.html
src/frontend/translate/messages.nl.xlf

Just in the source, so translation files need to be updated.

Fixed some text

---

src/frontend/translate/messages.de.xlf

I missed some texts visible only to normal users in #765. Surely Germanists would kill me for some translations...
Additionally now some more texts under settings. I'm unsure how much time I should invest here because admins would usually cope with English.

Some German translations, pt.3 (of ?)

---

angular.json
src/frontend/translate/messages.da.xlf

* Added Danish translation and missing english translation units

Danish translation added

---

src/common/DataStructureVersion.ts

DataStructureVersion bump to trigger database rebuild
https://github.com/bpatrik/pigallery2/issues/846#issuecomment-1985414513

DataStructureVersion bump to trigger database rebuild

---

src/backend/model/extension/ExtensionConfigWrapper.ts

Fixes #847
Tested against commit 3811fc3c

Fix extension configuration loading issue

---

package-lock.json
package.json
src/backend/model/extension/ExtensionConfigWrapper.ts
test/backend/integration/routers/admin/SettingsRouter.ts
test/backend/unit/model/extension/ExtensionConfigWrapper.spec.ts

This should move one step closer to #847 and https://github.com/bpatrik/pigallery2/issues/784

Improve extansion loading #847

---

extension/README.md

Correcting a grammatical error in a file Readme.md

docs: Change from intall to install

---

src/backend/model/database/SearchManager.ts
src/common/config/public/ClientConfig.ts

Fix for the search part of: https://github.com/bpatrik/pigallery2/issues/892

added coalesce to search queries in case offset is null

---

docker/alpine/Dockerfile.build
docker/debian-bookworm/Dockerfile.build
docker/debian-bullseye/Dockerfile.build
docker/debian-buster/Dockerfile.build
docker/debian-buster/selfcontained/Dockerfile

Should fix a bug whith IPv6 and healthcheck as shown in this issue: https://github.com/bpatrik/pigallery2/issues/894

Update Dockerfile.build - healthcheck changed from localhost to 127.0.0.1
