bpatrik/pigallery2

backend/middlewares/GalleryMWs.ts
Hi, thanks for creating pigallery2. Contributing back with a potential bug fix...
Issue:
1. Set up pigallery2 with videos settings disabled
2. Encountered this error while viewing on mobile (Chrome 72.0.3626.96 on Android 8.0.0). The gallery fails to load up; instead, just displays a loading image
```
2/10/2019, 2:26:38 AM[WARN] Handled error:
ErrorDTO {
code: 9,
message: 'Unknown server side error',
details:
TypeError: Cannot read property 'forEach' of undefined
at removeVideos_1 (/pigallery2-release/backend/middlewares/GalleryMWs.js:131:37)
at /pigallery2-release/backend/middlewares/GalleryMWs.js:131:67
at Array.forEach (<anonymous>)
at removeVideos_1 (/pigallery2-release/backend/middlewares/GalleryMWs.js:131:37)
at GalleryMWs.cleanUpGalleryResults …
```
=> Fix error on mobile when viewing pigallery2 with videos disabled

backend/model/threading/DiskMangerWorker.ts
For the most part, error messages look like:
```js
{ error: 
{ errno: -2,
code: 'ENOENT',
syscall: 'stat',
path: '/data/path/stuff/place' } }
```
But `toString()` just turns it into `[object Object]`, which is quite useless as a log message.
=> Remove .toString() from disk error handling

backend/model/threading/DiskMangerWorker.ts, common/config/private/IPrivateConfig.ts, common/config/private/PrivateConfigClass.ts, frontend/app/ui/settings/indexing/indexing.settings.component.html, frontend/app/ui/settings/indexing/indexing.settings.component.ts, frontend/app/ui/settings/settings.service.ts
This provides a mechanism to exclude folders from the index. Both by name, and by folders that contain a particular named file.
This should be a fix for issue #87
=> Ability to exclude directories, and config to choose them.

docker/alpine/Dockerfile.build, docker/debian-stretch/Dockerfile.build, docker/debian-stretch/selfcontained/Dockerfile
Makes it easier to change the options via ENV vars. Can be used to set the DB, IMAGE, TMP and CONF path.
=> Use ENV to set important paths

docker/docker-compose/with-mysql/docker-compose.yml
Fix for #163 
Prevents using memory database if db is still starting up
The server still starts up on first start with a sqlite db, but once you configure it to use mysql from the GUI, it uses that.
=> make app wait for db to start up first

src/frontend/app/ui/login/login.component.html
This will stop the browser from auto capitalizing the password on mobile and allow password managers to better save/load the password (especially on Android's Chrome).
=> Improve password field accessibility

src/frontend/app/ui/gallery/directories/directories.component.ts
This will force the directory grid to 2 columns on mobile.
=> Improve mobile directory grid layout

src/frontend/app/ui/gallery/map/map.service.ts
Old Mapbox classic styles and API have been deprecated then removed since June 2020. This PR changes the default Mapbox tiles to request the new API.
See <https://docs.mapbox.com/help/troubleshooting/migrate-legacy-static-tiles-api/>.
=> Replace old Mapbox tiles with Static Tiles API

docker/README.md
Correct definition of config volume. Previously, it would create a `config.json` folder on the host upon first creation of the container, which prevents the app to create the `config.json` file.
=> Fix docker instructions for running without docker-compose

src/backend/routes/PublicRouter.ts
In case `publicUrl` in the configuration is an empty string, then `start_url` for the `manifest.json` response is set to `.`.
=> Fixes #219: Manifest for web app takes '.' as default if publicUrl is empty string

src/frontend/app/ui/gallery/gallery.component.ts, src/frontend/app/ui/gallery/grid/grid.gallery.component.ts
This PR fixes the order issue in the gallery while sorting directories/media files:  
* Add code so directories can be sorted by date  
The code in `src/frontend/app/ui/gallery/gallery.component.ts` shows that `SortingMethods.ascDate` and `SortingMethods.ascName` ( and `desc` as well ) are using the same code to sort the directories ( both sort by name in natural-order ).  I've added some code so directories now can be sorted by its `lastModified` attribute.  
* Add code so media files in a directories can be sorted in natural-order  
PR #224 added the code to sort the directories in natural-order, however the media files in directories are still using lexicographic-order. I've added some code in `src/frontend/app/ui/gallery/grid/grid.gallery.component.ts` to support natural-order for …
=> Fix gallery order issue

src/frontend/app/ui/login/login.component.css, src/frontend/app/ui/sharelogin/share-login.component.css
Closes #265 
Just a simple edit following what I suggested in #265
=> CSS fix for truncated page titles on mobile

package-lock.json, package.json, src/frontend/app/ui/gallery/directories/directories.component.ts
Add user-agent based device detection and disable "portrait mode" for Desktop devices.
This resolves #279
=> Add device detection for portrait mode in directories listing

package.json, src/frontend/app/ui/gallery/gallery.component.ts, src/frontend/app/ui/gallery/grid/grid.gallery.component.ts
As mentioned in the issue, sorting by "ascending name" does not work as expected. This fix removes `natural-orderby` and uses `Intl.Collator` in its place.
=> Fix gallery sorting #341

src/frontend/app/ui/frame/frame.component.css
There is a whitespace between the Navbar and breadcrumb/sort section. The change here is to remove the margin style that causes the white space.
Screenshot:
=> Fix whitespace between Navbar and breadcrumbs

src/backend/model/threading/MetadataLoader.ts
This is a fix [which was also applied in exif reader](https://github.com/mattiasw/ExifReader/pull/47/files#diff-d65f0e04e026c207d67b8b88660ba72716c0e5363af90c7355ea04d1b9b256d6R120) to properly handle UTF-8 characters in face names. The problem only occurs in `exiftool` generated metadata as atttributes are accesed by raw values there (the "lightroom" version of face meta is fine).
Here is an example photo to illustrate the problem: https://transfer.sh/15gTYWl/IMG_5910.jpg
Without patch:
With patch:
=> fix encoding non-ascii characters in detected face names

src/backend/model/threading/MetadataLoader.ts
This breaks tests, so I had to revert it.
Reverts bpatrik/pigallery2#344
broken tests:
1) DiskMangerWorker
should parse metadata:
2) MetadataLoader
should load jpg:
=> Revert "fix encoding non-ascii characters in detected face names"

README.md, docs/index.html, src/backend/model/jobs/JobManager.ts, src/frontend/app/ui/settings/jobs/jobs.settings.component.html, src/frontend/translate/messages.cn.xlf, src/frontend/translate/messages.de.xlf, src/frontend/translate/messages.en.xlf, src/frontend/translate/messages.es.xlf, src/frontend/translate/messages.fr.xlf, src/frontend/translate/messages.hu.xlf, src/frontend/translate/messages.id.xlf, src/frontend/translate/messages.it.xlf, src/frontend/translate/messages.pl.xlf, src/frontend/translate/messages.ro.xlf, src/frontend/translate/messages.ru.xlf, src/frontend/translate/messages.sv.xlf
Replace instances of "an other" with "another" throughout the project.
This also touches translation files, which, I don't know if that causes negative effects in tooling.
=> Typo: replace "an other" with "another"

test/backend/assets/date_issue.json, test/backend/assets/orientation/broken_orientation_exif.json, test/backend/assets/test image öüóőúéáű-.,.json, test/backend/assets/xmp/xmp_subject.json
Good day.
I noticed the changes introduced by #536 did not update the test cases for parsing image metadata. Since #536 increased the number of decimal digits, the `exposure` attribute parsed from the images may have different values compared to the existing test data. Therefore, I made this PR to update the metadata on the test data.
=> Update the metadata on test image to match current implementation

src/common/config/private/PrivateConfig.ts
After some debugging, the custom options for fluent-ffmpeg are strict with spaces. We cannot have prefix or suffix spaces. The hint is confusing because it shows a space ` ` after semicolon `;`.
=> The spaces for ffmpeg custom options are strict.

src/backend/model/threading/VideoConverterWorker.ts
This is something with #597 
Without any ffmpeg output, I spend hours on investigating why my custom options are not working. I cannot find the logs in UI output or command line output. This change will redirect ALL OF ffmpeg output to pigallery2's logger.
Warning: ffmpeg will output tons of information and bump your output. 
https://www.npmjs.com/package/fluent-ffmpeg#stderr-ffmpeg-output
=> Redirect ffmpeg output to logger.

docs/index.html
The feature to override the default sort order was not yet documented, so I added it.
=> document issue #177 about overriding default sort order

docs/style.css
The list is displayed in a weird way in the “All features:” section of https://bpatrik.github.io/pigallery2/ :
> ![image](https://github.com/bpatrik/pigallery2/assets/2071331/f3998225-32e9-4c09-821a-d91e2d8f0950)
This PR restore the `text-align` so that it's easier to read:
> ![image](https://github.com/bpatrik/pigallery2/assets/2071331/9e3d8b60-7dad-48d3-9c80-89da4f6f74a1)
=> docs: fix text-align in list

demo/images/IMG_5910.jpg.xmp, demo/images/bunny.mp4.xmp, package-lock.json, package.json, src/backend/model/fileaccess/MetadataLoader.ts, src/common/entities/ConentWrapper.ts, src/common/entities/VideoDTO.ts
This pull request adds xmp sidecar support using exifr in order to gain access to keywords metadata for video files. It can be extended to collect additional data for videos or photos and is a first step towards reducing the number of exif readers per #277 .
This is a first step towards #156 
Exifr was chosen per #277 
Work accelerated by reviewing exiftool code from @mcdamo on #294
Known limitation of this pull request:
-Keywords for videos do not show up in the info panel but tagged videos are returned when you search for the keyword.
It's unclear to me why the tags do not show up in the info panel on the videos. **If you search for keyword:test or keyword:rabbit you will get back the bunny.mp4 video**, suggesting they are correctly recorded in the database. 
I attempted modification of …
=> Add XMP sidecar support in backend for video files

src/frontend/translate/messages.de.xlf
Version 2.0.0 brings a few very nice features, I like pigallery2 more than ever!
Hopefully my translations can help a bit. Yes, not too much, but now some non-admin-texts are translated again. I might add more, whenever I find the time
I used the word "Anwendung" (en: application) where "app" was used in English. Although "app" gets into German more and more it's still not as clear as in English, especially with web apps. I can change that, if required, or just do it yourself.
=> Some German translations

demo/images/IMG_5910.jpg.xmp, demo/images/bunny.mp4.xmp, src/backend/model/fileaccess/MetadataLoader.ts, src/common/entities/ConentWrapper.ts, src/common/entities/MediaDTO.ts, src/common/entities/PhotoDTO.ts, src/common/entities/VideoDTO.ts
Added ratings to xmp sidecar support, also added rating to bunny.mp4.xmp and a different rating in IMG_5910.jpg.xmp vs what is in the photo file to test if sidecar is functioning as primary (it is as discussed).
=> Added ratings to xmp sidecar support

src/frontend/translate/messages.de.xlf
Fix to address [a comment](https://github.com/bpatrik/pigallery2/commit/161a5fc417258b63fcc5e9900f3d0676340952c4#commitcomment-134117343) pointing out an erroneous translation / mostly bad wording.
=> Tiny fix of error in German translation

src/backend/routes/GalleryRouter.ts
Route collision with thumbnail path and video path. Results in videos not loading properly.
Changing the route definition order fixes the issue.
=> Fix video not loading #808

docker/alpine/Dockerfile.build
Unlike debian that pulled heif libs when install vips-dev, alpine need to install this heif separately.
=> Manually add vips-heif

docker/debian-bullseye/Dockerfile.build, docker/debian-buster/Dockerfile.build
Building sharp module with respective distro vips libs.
=> Add heif support via VIPS (debian docker image)

src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.ts
This addresses my issue #835 and is two fold:
1. Previously, any non-negative deltaY change to the mouse wheel would cause a photo in the lightbox zoom out, regardless of the direction. I have changed this so that zoom out is only possible with positive deltaY values.
2. I have added the option to scroll through photos in the lightbox using horizontal scrolling (deltaX). This mimics the behavior of left/right arrow and allows for navigation solely with the mouse. I've also changed it so you _can_ use this scroll on videos. The previous behavior of canceling zoom on videos remains.
Thanks for the consideration!
=> Lightbox: fix mouse wheel behavior and add horizontal scroll feature.

src/backend/Logger.ts, src/backend/server.ts
Allow for anonymous functions in logging calls.
The function is only called if the message is logged. (e.g. if the verbosity is turned up high enough.)
This allows for expensive operations to be avoided in cases where the logging won't happen.
The idea is that this provides a performance benefit. I don't know how "expensive" an operation must be
to actually realize a performance benefit, though.
I added an example in `server.ts`...
It's probably "expensive" to dump the configuration to JSON, then stringify that JSON for logging.
I originally implemented something similar in my 'digikam-connector' extension, where I used it to log the inputs/outputs of the extension hooks while I was developing and debugging.  I figured that running `util.inspect()` on everything was undesirable in a …
=> Add logging elision

src/backend/model/extension/ExtensionManager.ts, src/backend/model/extension/IExtension.ts, src/backend/model/fileaccess/DiskManager.ts
Without this, the mechanism to exclude a directory from indexing is a bit strange.  I had to use the `scanDirectory.after` hook, then remove elements from the `output.directories` array.
In order to make the extension hook a bit more developer-friendly, I also changed the arguments to the `excludeDir` function to be a dictionary instead of just an array (or tuple?) of strings.
Tested and working against commit f5f34c5 with a tweaked version of my 'digikam connector' extension.
=> Add excludeDir to extension interface

src/frontend/app/ui/gallery/grid/photo/photo.grid.gallery.component.ts, src/frontend/app/ui/gallery/lightbox/controls/controls.lightbox.gallery.component.ts, src/frontend/app/ui/gallery/lightbox/infopanel/info-panel.lightbox.gallery.component.ts
* Show comma-separated city, state and country in infobox and in gallery mode. All of the values that are non-empty will be shown.
Before:
After:
=> Feature/location info (#9)

src/backend/model/fileaccess/MetadataLoader.ts, test/backend/assets/sidecar/metadata_v2.json
Avoid getting Rating of 0 when rating metadata is not included in a sidecar.
=> Deal with rating missing in XMP sidecars

src/common/Utils.ts, src/frontend/app/ui/gallery/navigator/sorting.service.ts, test/common/unit/Utils.spec.ts
Fixes #518
I've described the root cause in this comment on the issue: https://github.com/bpatrik/pigallery2/issues/518#issuecomment-2026473493
To test:
- Checkout the branch and rename some of the demo images to `10`, `10.1`, `10.2`, etc.
- Run the app and confirm that they now sort as expected according to the issue (10, 10.1, 10.2 rather than 10.1, 10.2, 10).
- Download a PNG ([here's a small filesized CC0 one from Wikimedia Commons you can use](https://commons.wikimedia.org/w/index.php?curid=931234) and name it 10.png in the demo images folder. Reverse the name sorting a couple times and confirm that 10.jpg and 10.png correctly trade places and sort alphabetically by their full filename. This test is crucial to confirm consistency in the name output, otherwise the identical …
=> Trim extensions when sorting filenames

docker/docker-compose/default/nginx.conf
TLS 1.3 has been supported in nginx since 2018. This change brings nginx.conf to parity with what nginx recommends by default.
=> Enable TLS 1.3 in nginx.conf

src/backend/model/fileaccess/PhotoWorker.ts
qscale=4 provides bad quality for webp video thumbnails. qscale=50 creates better results and has a comparable size to image thumbnails.
=> Provide more reasonable quality for webp video thumbnails

src/backend/middlewares/user/AuthenticationMWs.ts, src/backend/server.ts, src/common/config/private/PrivateConfig.ts
Fixes #1014 
Add support for [express trust proxy](https://expressjs.com/en/guide/behind-proxies.html) and remote client IP in failed authentication logs.
=> [Logging] Add remote IP log context on authn failure
